"""
Django settings for worklog project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# === FLAW 4: A05 Security Misconfiguration ===
# Three production-unsafe defaults are active simultaneously:
#   * SECRET_KEY hardcoded in source (anyone who reads the repo gets it
#     and can forge sessions / password-reset tokens).
#   * DEBUG = True — Django's interactive error page is rendered on any
#     unhandled exception, leaking settings, environment variables,
#     installed apps, SQL, traceback, and the SECRET_KEY itself.
#   * ALLOWED_HOSTS = ['*'] — every Host header is accepted, defeating
#     Host-header validation and enabling cache poisoning / password-
#     reset spoofing.
# See README section "Reproducing Flaw 4" for steps.
SECRET_KEY = 'django-insecure-czyq^ylyla38wdfz)mndf7x9v-a@lpsm8!gn%s5%4==y*3#dni'
DEBUG = True
ALLOWED_HOSTS = ['*']

# === FIX (commented out — uncomment to apply) ===
# Load SECRET_KEY from the environment (set DJANGO_SECRET_KEY before
# running). Turn DEBUG off so unhandled errors render a generic 500
# page with no internals. Limit ALLOWED_HOSTS to the deployed hostnames.
# SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
# DEBUG = False
# ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracker',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'entry_list'
LOGOUT_REDIRECT_URL = 'login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'worklog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'worklog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# === FLAW 5: A07 Identification and Authentication Failures ===
# AUTH_PASSWORD_VALIDATORS is empty, so calls to validate_password() are
# no-ops. Combined with the bypass in tracker/views.py:register (which
# does not call validate_password() at all), anything passes — "1",
# "abc", "password", numeric-only, similar-to-username, etc.
# See README section "Reproducing Flaw 5" for steps.
AUTH_PASSWORD_VALIDATORS = []

# === FIX (commented out — uncomment to apply) ===
# Re-enable Django's four standard password validators. The matching
# half of the fix lives in tracker/views.py:register, which calls
# password_validation.validate_password() before saving the new user.
# AUTH_PASSWORD_VALIDATORS = [
#     {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
# ]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
